runtime: java11
env: standard
service: kotlin-grpc-client
entrypoint: >
  java
  -server
  -XX:+DisableExplicitGC
  -agentpath:/opt/cdbg/cdbg_java_agent.so=--log_dir=/var/log
  -agentpath:/opt/cprof/profiler_java_agent.so=-logtostderr,-cprof_enable_heap_sampling=true
  -jar client-all.jar

instance_class: F2
automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_concurrent_requests: 10
  min_pending_latency: 15000ms

handlers:
  - url: .*
    secure: always
    script: auto
