micronaut:
  application:
    name: kotlinGrpcClient
grpc-server:
  host: localhost
  port: 14552
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    greeter:
      address: '${grpc-server.host}:${grpc-server.port}'
      plaintext: true
      max-retry-attempts: 3
